<?php
namespace Database\Seeders;
use App\Models\Tutor;
use Illuminate\Database\Seeder;

class TutorSeeder extends Seeder {
    public function run(): void {
        $tutors = [
            [
                'name' => 'Angeline',
                'slug' => 'angeline',
                'tagline' => 'Accomplished pianist & violinist with Trinity College London certification',
                'qualification' => 'ATCL in Piano; Trinity College London Grade 8 (Piano & Violin)',
                'experience_years' => null,
                'subjects' => 'Piano, Violin',
                'fee_hourly' => 700,
                'fee_trial' => 0,
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'localities' => 'New Town, Salt Lake, Ballygunge, Online',
                'languages' => 'English',
                'teaching_mode' => 'online',
                'verified' => true,
                'is_published' => true,
                'bio' => 'Angeline is an accomplished musician with comprehensive classical training in both piano and violin, having completed all 8 grades through Trinity College London examinations. She holds the ATCL diploma in Piano and brings deep technical knowledge and a nurturing teaching style to every session.',
                'image_url' => 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Untitled-design-63-760x1024-1.png',
                'position' => 0,
            ],
            [
                'name' => 'Anney',
                'slug' => 'anney',
                'tagline' => 'MBA & IDP IELTS Trainer with 15+ years in language education',
                'qualification' => 'MBA — Mahatma Gandhi University; IDP Certified IELTS Trainer',
                'experience_years' => 15,
                'subjects' => 'English, IELTS Training, Spoken English',
                'fee_hourly' => 750,
                'fee_trial' => 0,
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'localities' => 'New Town, Salt Lake, Ballygunge, Online',
                'languages' => 'English, Hindi',
                'teaching_mode' => 'online',
                'verified' => true,
                'is_published' => true,
                'bio' => 'Anney is a seasoned language educator with over 15 years of expertise in training, storytelling, and IELTS preparation. Holding an MBA from Mahatma Gandhi University and IDP IELTS certification, she crafts engaging, personalised lessons that build both fluency and exam confidence in her students.',
                'image_url' => 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Untitled-design-59-760x1024-1.png',
                'position' => 1,
            ],
            [
                'name' => 'Anubrato',
                'slug' => 'anubrato',
                'tagline' => 'ABRSM certified music educator trained at Wuerzburg University, Germany',
                'qualification' => 'ABRSM certified; Teacher Training & Pedagogy — University of Wuerzburg, Germany',
                'experience_years' => null,
                'subjects' => 'Music Theory, Piano, Guitar',
                'fee_hourly' => 750,
                'fee_trial' => 0,
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'localities' => 'New Town, Salt Lake, Ballygunge, Online',
                'languages' => 'English, Bengali',
                'teaching_mode' => 'online',
                'verified' => true,
                'is_published' => true,
                'bio' => 'Anubrato is a formally trained music educator with German pedagogical credentials from the University of Wuerzburg and ABRSM certification. His structured yet creative teaching method helps students build a strong musical foundation while developing a genuine love for the craft.',
                'image_url' => 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Untitled-design-64-760x1024-1.png',
                'position' => 2,
            ],
            [
                'name' => 'Deana',
                'slug' => 'deana',
                'tagline' => 'Piano instructor with MBA and Trinity College London Grade 6 certification',
                'qualification' => 'MBA; Trinity College London Grade 6 Piano',
                'experience_years' => null,
                'subjects' => 'Piano',
                'fee_hourly' => 650,
                'fee_trial' => 0,
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'localities' => 'New Town, Salt Lake, Ballygunge, Online',
                'languages' => 'English',
                'teaching_mode' => 'online',
                'verified' => true,
                'is_published' => true,
                'bio' => 'Deana combines advanced academic credentials with formal conservatory training, having completed Grade 6 in Piano through Trinity College London. Her lessons are structured, encouraging, and tailored to each student\'s pace — whether they are a complete beginner or looking to advance to performance level.',
                'image_url' => 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Untitled-design-65-760x1024-1.png',
                'position' => 3,
            ],
            [
                'name' => 'Kainaaz',
                'slug' => 'kainaaz',
                'tagline' => 'Gold Medallist in Bharatnatyam | Broadway Dance Center, New York',
                'qualification' => 'Masters in Performing Arts — Gold Medallist in Bharatnatyam; trained at Broadway Dance Center, New York (Ballet, Tap, Contemporary)',
                'experience_years' => null,
                'subjects' => 'Bharatnatyam, Ballet, Tap Dance, Contemporary Dance, Dance',
                'fee_hourly' => 1000,
                'fee_trial' => 0,
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'localities' => 'New Town, Salt Lake, Ballygunge, Online',
                'languages' => 'English, Hindi',
                'teaching_mode' => 'online',
                'verified' => true,
                'is_published' => true,
                'bio' => 'Kainaaz holds a Masters in Performing Arts with a Gold Medal in Bharatnatyam and has trained in Ballet, Tap, and Contemporary dance at the prestigious Broadway Dance Center in New York. Her multi-disciplinary background enables her to teach classical Indian and Western dance forms with equal depth and artistry.',
                'image_url' => 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Untitled-design-60-760x1024-1.png',
                'position' => 4,
            ],
            [
                'name' => 'Nisitha',
                'slug' => 'nisitha',
                'tagline' => 'C2-level Spanish educator with 7+ years of school and college teaching experience',
                'qualification' => 'Advanced Diploma in Spanish Language (C2 Level)',
                'experience_years' => 7,
                'subjects' => 'Spanish Language',
                'fee_hourly' => 700,
                'fee_trial' => 0,
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'localities' => 'New Town, Salt Lake, Ballygunge, Online',
                'languages' => 'English, Hindi, Spanish',
                'teaching_mode' => 'online',
                'verified' => true,
                'is_published' => true,
                'bio' => 'Nisitha holds an Advanced Diploma in Spanish at the C2 (proficiency) level and brings over 7 years of experience teaching Spanish to school and college students. Her lessons focus on real-world conversational fluency alongside grammar mastery and exam preparation.',
                'image_url' => 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Untitled-design-66-760x1024-1.png',
                'position' => 5,
            ],
            [
                'name' => 'Pinki',
                'slug' => 'pinki',
                'tagline' => 'World & Asian Yoga Championship Gold Medallist | 20+ years teaching experience',
                'qualification' => 'Master in Yoga & Naturopathy — Punjab University; Gold Medallist, World & Asian Yoga Championships',
                'experience_years' => 20,
                'subjects' => 'Yoga, Naturopathy, Wellness',
                'fee_hourly' => 800,
                'fee_trial' => 0,
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'localities' => 'New Town, Salt Lake, Ballygunge, Online',
                'languages' => 'English, Hindi, Punjabi',
                'teaching_mode' => 'online',
                'verified' => true,
                'is_published' => true,
                'bio' => 'Pinki is an internationally decorated yoga practitioner holding a Master\'s degree in Yoga and Naturopathy from Punjab University. A Gold Medallist at both the World and Asian Yoga Championships with over 20 years of teaching experience, she guides students of all levels toward physical and mental wellness through structured, safe, and inspiring sessions.',
                'image_url' => 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Untitled-design-61-760x1024-1.png',
                'position' => 6,
            ],
            [
                'name' => 'Prashasti',
                'slug' => 'prashasti',
                'tagline' => 'Piano educator with Trinity College London certification and University of Mumbai background',
                'qualification' => 'University of Mumbai; Trinity College London Grade 6 Piano',
                'experience_years' => null,
                'subjects' => 'Piano',
                'fee_hourly' => 650,
                'fee_trial' => 0,
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'localities' => 'New Town, Salt Lake, Ballygunge, Online',
                'languages' => 'English, Hindi, Marathi',
                'teaching_mode' => 'online',
                'verified' => true,
                'is_published' => true,
                'bio' => 'Prashasti studied at the University of Mumbai and has completed Grade 6 in Piano through Trinity College London. She creates a warm, encouraging learning environment that helps students progress from fundamentals to confident performance at their own pace.',
                'image_url' => 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Untitled-design-67-760x1024-1.png',
                'position' => 7,
            ],
            [
                'name' => 'Rahul',
                'slug' => 'rahul',
                'tagline' => 'B.Tech engineer with 5+ years in technology education and industry',
                'qualification' => 'B.Tech — Dr M.G.R University',
                'experience_years' => 5,
                'subjects' => 'Python Programming, AI & Machine Learning, Web Development, Computer Science',
                'fee_hourly' => 700,
                'fee_trial' => 0,
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'localities' => 'New Town, Salt Lake, Ballygunge, Online',
                'languages' => 'English, Hindi, Tamil',
                'teaching_mode' => 'online',
                'verified' => true,
                'is_published' => true,
                'bio' => 'Rahul holds a B.Tech from Dr M.G.R University and brings over 5 years of professional experience spanning software development and technology education. He specialises in Python, AI/ML fundamentals, and web development, making complex concepts accessible and engaging for students at every level.',
                'image_url' => 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Untitled-design-68-760x1024-1.png',
                'position' => 8,
            ],
            [
                'name' => 'Shamim',
                'slug' => 'shamim',
                'tagline' => 'Conservatoire-trained multi-instrumentalist | ABRSM Grade 8 Violin & Theory',
                'qualification' => 'Bachelor of Music Arts — Georgia State Conservatoire; ABRSM Grade 8 Violin & Music Theory; ABRSM Grade 6 Piano',
                'experience_years' => null,
                'subjects' => 'Violin, Music Theory, Piano',
                'fee_hourly' => 800,
                'fee_trial' => 0,
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'localities' => 'New Town, Salt Lake, Ballygunge, Online',
                'languages' => 'English',
                'teaching_mode' => 'online',
                'verified' => true,
                'is_published' => true,
                'bio' => 'Shamim holds a Bachelor of Music Arts from the Georgia State Conservatoire and has achieved Grade 8 in both Violin and Music Theory and Grade 6 in Piano through ABRSM. As a classically trained multi-instrumentalist, she delivers rigorous yet inspiring lessons that nurture technical precision and genuine musicality.',
                'image_url' => 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Untitled-design-62-760x1024-2.png',
                'position' => 9,
            ],
            [
                'name' => 'Surajit',
                'slug' => 'surajit',
                'tagline' => 'Professional drummer and percussionist with 9 years of performance & teaching experience',
                'qualification' => 'Professional Drummer & Percussionist',
                'experience_years' => 9,
                'subjects' => 'Drums, Percussion',
                'fee_hourly' => 700,
                'fee_trial' => 0,
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'localities' => 'New Town, Salt Lake, Ballygunge, Online',
                'languages' => 'English, Bengali, Hindi',
                'teaching_mode' => 'online',
                'verified' => true,
                'is_published' => true,
                'bio' => 'Surajit is a skilled percussion specialist with nearly a decade of professional experience across live performance and music education. He teaches a full range of drumming styles — from beginners learning basic rhythm to advanced students working on complex patterns and fills — in an energetic and methodical way.',
                'image_url' => 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Untitled-design-69-760x1024-2.png',
                'position' => 10,
            ],
            [
                'name' => 'Vijayalakshmi',
                'slug' => 'vijayalakshmi',
                'tagline' => 'Gold Medallist vocalist | Carnatic, Hindustani & Western singing',
                'qualification' => 'Bachelor in Music — Gold Medallist',
                'experience_years' => null,
                'subjects' => 'Vocal Music, Carnatic Vocals, Hindustani Vocals, Western Vocals',
                'fee_hourly' => 700,
                'fee_trial' => 0,
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'localities' => 'New Town, Salt Lake, Ballygunge, Online',
                'languages' => 'English, Tamil, Telugu, Hindi',
                'teaching_mode' => 'online',
                'verified' => true,
                'is_published' => true,
                'bio' => 'Vijayalakshmi is an accomplished vocalist who graduated with a Gold Medal in Music. She is trained across Carnatic, Hindustani, and Western vocal traditions, enabling her to guide students in whichever style they wish to pursue. Her lessons combine rigorous raga training with expressive performance coaching.',
                'image_url' => 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Untitled-design-70-760x1024-2.png',
                'position' => 11,
            ],
            [
                'name' => 'Vipul',
                'slug' => 'vipul',
                'tagline' => 'Seasoned CS educator | B.Sc Computer Science, University of Delhi',
                'qualification' => 'Bachelor of Computer Science — University of Delhi',
                'experience_years' => null,
                'subjects' => 'Computer Science, Python Programming, Java, Web Development, Data Science',
                'fee_hourly' => 750,
                'fee_trial' => 0,
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'localities' => 'New Town, Salt Lake, Ballygunge, Online',
                'languages' => 'English, Hindi',
                'teaching_mode' => 'online',
                'verified' => true,
                'is_published' => true,
                'bio' => 'Vipul holds a Bachelor of Computer Science from the University of Delhi and brings extensive hands-on industry experience to his teaching. He covers Python, Java, web development, and data science fundamentals, breaking down complex technical concepts into clear, project-based lessons that build real-world skills.',
                'image_url' => 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Untitled-design-71-760x1024-2.png',
                'position' => 12,
            ],
        ];

        foreach ($tutors as $data) {
            Tutor::updateOrCreate(['slug' => $data['slug']], $data);
        }

        $this->command->info('Seeded '.count($tutors).' tutors.');
    }
}
