-- IndiaTutors Online — Phase 1 database
-- Import this in phpMyAdmin: Databases tab → create `indiatutors` → Import → choose this file
-- OR: paste directly into phpMyAdmin's SQL tab after selecting the `indiatutors` database

CREATE DATABASE IF NOT EXISTS `indiatutors` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `indiatutors`;

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `category_course`;
DROP TABLE IF EXISTS `courses`;
DROP TABLE IF EXISTS `categories`;
DROP TABLE IF EXISTS `demo_requests`;
DROP TABLE IF EXISTS `contact_messages`;
SET FOREIGN_KEY_CHECKS = 1;


-- ================================================================
-- SCHEMA
-- ================================================================

CREATE TABLE `categories` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `parent_id` BIGINT UNSIGNED NULL,
  `image_url` VARCHAR(500) NULL,
  `description` TEXT NULL,
  `position` INT UNSIGNED NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `categories_slug_unique` (`slug`),
  KEY `categories_parent_id_index` (`parent_id`),
  CONSTRAINT `categories_parent_id_foreign` FOREIGN KEY (`parent_id`)
    REFERENCES `categories` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `courses` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sku` VARCHAR(120) NULL,
  `name` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `short_description` TEXT NULL,
  `description` LONGTEXT NULL,
  `regular_price` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `sale_price` DECIMAL(10,2) NULL,
  `image_url` VARCHAR(500) NULL,
  `is_featured` TINYINT(1) NOT NULL DEFAULT 0,
  `is_published` TINYINT(1) NOT NULL DEFAULT 1,
  `position` INT UNSIGNED NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `courses_slug_unique` (`slug`),
  UNIQUE KEY `courses_sku_unique` (`sku`),
  KEY `courses_is_published_index` (`is_published`),
  KEY `courses_is_featured_index` (`is_featured`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `category_course` (
  `category_id` BIGINT UNSIGNED NOT NULL,
  `course_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`category_id`,`course_id`),
  KEY `category_course_course_id_foreign` (`course_id`),
  CONSTRAINT `category_course_category_id_foreign` FOREIGN KEY (`category_id`)
    REFERENCES `categories` (`id`) ON DELETE CASCADE,
  CONSTRAINT `category_course_course_id_foreign` FOREIGN KEY (`course_id`)
    REFERENCES `courses` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `demo_requests` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  `email` VARCHAR(180) NOT NULL,
  `phone_country_code` VARCHAR(6) NOT NULL DEFAULT '+91',
  `phone` VARCHAR(20) NOT NULL,
  `subject` VARCHAR(120) NULL,
  `grade` VARCHAR(40) NULL,
  `board` VARCHAR(20) NULL,
  `mode` VARCHAR(20) NULL,
  `city` VARCHAR(80) NULL,
  `country` VARCHAR(80) NOT NULL DEFAULT 'India',
  `timezone` VARCHAR(60) NULL,
  `message` TEXT NULL,
  `whatsapp_consent` TINYINT(1) NOT NULL DEFAULT 0,
  `marketing_consent` TINYINT(1) NOT NULL DEFAULT 0,
  `course_id` BIGINT UNSIGNED NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'new',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `demo_requests_status_index` (`status`),
  KEY `demo_requests_created_at_index` (`created_at`),
  KEY `demo_requests_course_id_foreign` (`course_id`),
  CONSTRAINT `demo_requests_course_id_foreign` FOREIGN KEY (`course_id`)
    REFERENCES `courses` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `contact_messages` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  `email` VARCHAR(180) NOT NULL,
  `phone` VARCHAR(20) NULL,
  `subject` VARCHAR(200) NULL,
  `message` TEXT NOT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'new',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ================================================================
-- DATA: 112 categories
-- ================================================================

INSERT INTO `categories` (`id`, `name`, `slug`, `parent_id`) VALUES
  (1, 'IT Technologies for Kids', 'it-technologies-for-kids', NULL),
  (2, 'Academics', 'academics', NULL),
  (3, 'Mind Sports', 'mind-sports', NULL),
  (4, 'Music', 'music', NULL),
  (5, 'AP Courses', 'ap-courses', NULL),
  (6, 'Standardized Tests', 'standardized-tests', NULL),
  (7, 'Guitar', 'guitar', NULL),
  (8, 'Piano', 'piano', NULL),
  (9, 'Coding', 'coding', NULL),
  (10, 'Python', 'python', NULL),
  (11, 'Languages', 'languages', NULL),
  (12, 'Spoken English', 'spoken-english', NULL),
  (13, 'Musical Instruments', 'musical-instruments', NULL),
  (14, 'Ukulele', 'ukulele', 13),
  (15, 'Keyboard', 'keyboard', 13),
  (16, 'Drums', 'drums', 13),
  (17, 'Violin', 'violin', 13),
  (18, 'Veena', 'veena', 13),
  (19, 'Cello', 'cello', 13),
  (20, 'Viola', 'viola', 13),
  (21, 'Clarinet', 'clarinet', 13),
  (22, 'Tabla', 'tabla', 13),
  (23, 'Indian Flute', 'indian-flute', 13),
  (24, 'Western Flute', 'western-flute', 13),
  (25, 'Saxophone', 'saxophone', 13),
  (26, 'Music Theory', 'music-theory', 13),
  (27, 'Trumpet', 'trumpet', 13),
  (28, 'Sitar', 'sitar', 13),
  (29, 'Recorder', 'recorder', 13),
  (30, 'Carnatic Violin', 'carnatic-violin', 13),
  (31, 'Vocal Music', 'vocal-music', NULL),
  (32, 'Carnatic', 'carnatic', 31),
  (33, 'Hindustani', 'hindustani', 31),
  (34, 'Western', 'western', 31),
  (35, 'IT Technologies', 'it-technologies', NULL),
  (36, 'Scratch', 'scratch', 35),
  (37, 'Blockly', 'blockly', 35),
  (38, 'Roblox & Minecraft', 'roblox-minecraft', 35),
  (39, 'Java', 'java', 35),
  (40, 'C++', 'c', 35),
  (41, 'Web Development', 'web-development', 35),
  (42, 'MIT App Inventor', 'mit-app-inventor', 35),
  (43, 'Robotics', 'robotics', 35),
  (44, 'AI & ML', 'ai-ml', 35),
  (45, 'Data Science', 'data-science', 35),
  (46, 'AI Prompting', 'ai-prompting', 35),
  (47, 'Graphics Design', 'graphics-design', 35),
  (48, 'Video Editing', 'video-editing', 35),
  (49, 'Animation', 'animation', 35),
  (50, 'VFX', 'vfx', 35),
  (51, 'AWS', 'aws', 35),
  (52, 'DevOps', 'devops', 35),
  (53, 'Rubik''s Cube', 'rubik-s-cube', 3),
  (54, 'Chess', 'chess', 3),
  (55, 'Creative Skills', 'creative-skills', NULL),
  (56, 'Arts & Painting', 'arts-painting', 55),
  (57, 'Creative Writing', 'creative-writing', 55),
  (58, 'Public Speaking', 'public-speaking', 55),
  (59, 'Spelling Competition', 'spelling-competition', 55),
  (60, 'Dance', 'dance', NULL),
  (61, 'Bollywood', 'bollywood', 60),
  (62, 'Kuchipudi', 'kuchipudi', 60),
  (63, 'Bharatnatyam', 'bharatnatyam', 60),
  (64, 'Kathak', 'kathak', 60),
  (65, 'Hip Hop', 'hip-hop', 60),
  (66, 'Zumba', 'zumba', 60),
  (67, 'Western Dance', 'western-dance', 60),
  (68, 'Spanish', 'spanish', 11),
  (69, 'French', 'french', 11),
  (70, 'German', 'german', 11),
  (71, 'Mandarin', 'mandarin', 11),
  (72, 'Russian', 'russian', 11),
  (73, 'Sanskrit', 'sanskrit', 11),
  (74, 'Hindi', 'hindi', 11),
  (75, 'Tamil', 'tamil', 11),
  (76, 'Telugu', 'telugu', 11),
  (77, 'Kannada', 'kannada', 11),
  (78, 'Malayalam', 'malayalam', 11),
  (79, 'Academics — Elementary & Middle School', 'academics-elementary-middle-school', NULL),
  (80, 'Phonics', 'phonics', 79),
  (81, 'Mathematics', 'mathematics', 79),
  (82, 'Vedic Maths', 'vedic-maths', 79),
  (83, 'English', 'english', 79),
  (84, 'Science', 'science', 79),
  (85, 'Social Studies', 'social-studies', 79),
  (86, 'Abacus', 'abacus', 79),
  (87, 'Academics — High School', 'academics-high-school', NULL),
  (88, 'Physics', 'physics', 87),
  (89, 'Chemistry', 'chemistry', 87),
  (90, 'Biology', 'biology', 87),
  (91, 'Algebra', 'algebra', 87),
  (92, 'Geometry', 'geometry', 87),
  (93, 'Calculus', 'calculus', 87),
  (94, 'Essay Writing', 'essay-writing', 87),
  (95, 'Economics', 'economics', 87),
  (96, 'Honors', 'honors', 87),
  (97, 'AP Physics', 'ap-physics', 5),
  (98, 'AP Chemistry', 'ap-chemistry', 5),
  (99, 'AP Biology', 'ap-biology', 5),
  (100, 'AP Calculus', 'ap-calculus', 5),
  (101, 'AP Languages', 'ap-languages', 5),
  (102, 'AP Computer Science', 'ap-computer-science', 5),
  (103, 'AP History', 'ap-history', 5),
  (104, 'AP Statistics', 'ap-statistics', 5),
  (105, 'AP Music Theory', 'ap-music-theory', 5),
  (106, 'AP Economics', 'ap-economics', 5),
  (107, 'English SAT/PSAT', 'english-sat-psat', 6),
  (108, 'Math SAT/PSAT', 'math-sat-psat', 6),
  (109, 'NMSQT', 'nmsqt', 6),
  (110, 'ACT', 'act', 6),
  (111, 'Art and Craft', 'art-and-craft', 55),
  (112, 'Digital SAT/PSAT Math', 'digital-sat-psat-math', 6);

-- ================================================================
-- DATA: 134 courses
-- ================================================================

INSERT INTO `courses` (`id`, `sku`, `name`, `slug`, `short_description`, `description`, `regular_price`, `sale_price`, `image_url`, `is_featured`, `is_published`, `position`) VALUES
  (1, 'ito-ai-ml', 'Artificial Intelligence & Machine Learning', 'artificial-intelligence-machine-learning', 'Hands-on AI/ML course covering model basics, practical datasets, and guided mini projects.', 'Hands-on AI/ML course covering model basics, practical datasets, and guided mini projects.', 1000.0, 750.0, 'https://indiatutorsonline.com/wp-content/uploads/2026/04/AIML.webp', 0, 1, 0),
  (2, 'ito-python', 'Python Programming for Beginners', 'python-programming-for-beginners', 'Start coding with Python through live sessions, assignments, and mentor feedback.', 'Start coding with Python through live sessions, assignments, and mentor feedback.', 1000.0, 750.0, 'https://indiatutorsonline.com/wp-content/uploads/2026/04/PythonCarouselCover.webp', 0, 1, 0),
  (3, 'ito-robotics', 'Robotics & Computational Thinking', 'robotics-computational-thinking', 'Build logic and automation skills with beginner robotics concepts and project work.', 'Build logic and automation skills with beginner robotics concepts and project work.', 1000.0, 750.0, 'https://indiatutorsonline.com/wp-content/uploads/2026/04/RoboticsCarouselCover.webp', 0, 1, 0),
  (4, 'ito-algebra', 'Algebra I Foundation', 'algebra-i-foundation', 'Concept-to-application algebra training for middle and high school learners.', 'Concept-to-application algebra training for middle and high school learners.', 1000.0, 750.0, 'https://indiatutorsonline.com/wp-content/uploads/2026/04/Algebra1Carousel.webp', 0, 1, 0),
  (5, 'ito-chess', 'Chess Strategy & Mind Sports', 'chess-strategy-mind-sports', 'Structured chess coaching focused on openings, tactics, and tournament readiness.', 'Structured chess coaching focused on openings, tactics, and tournament readiness.', 1000.0, 750.0, 'https://indiatutorsonline.com/wp-content/uploads/2026/04/Chess.jpg', 0, 1, 0),
  (6, 'ito-violin', 'Violin/Viola Lessons for Beginners', 'violin-viola-lessons-for-beginners', 'Beginner-friendly violin and viola classes with technique drills and repertoire guidance.', 'Beginner-friendly violin and viola classes with technique drills and repertoire guidance.', 1000.0, 750.0, 'https://indiatutorsonline.com/wp-content/uploads/2026/04/Violin.webp', 0, 1, 0),
  (7, 'ito-ap-physics', 'AP Physics Prep', 'ap-physics-prep', 'AP-aligned physics prep with concept boosters, timed practice, and exam strategy.', 'AP-aligned physics prep with concept boosters, timed practice, and exam strategy.', 1000.0, 750.0, 'https://indiatutorsonline.com/wp-content/uploads/2026/04/App-Developement.jpg', 0, 1, 0),
  (8, 'ito-sat-math', 'SAT/PSAT Math Mastery', 'sat-psat-math-mastery', 'Targeted SAT and PSAT math preparation with diagnostics and score-improvement plans.', 'Targeted SAT and PSAT math preparation with diagnostics and score-improvement plans.', 1000.0, 750.0, 'https://indiatutorsonline.com/wp-content/uploads/2026/04/AIMLCarouselCover.webp', 0, 1, 0),
  (9, NULL, 'Customized Online Guitar Lessons for Kids — Basics to Mastery', 'customized-online-guitar-lessons-for-kids-basics-to-mastery', 'Live guitar classes with expert mentors. Flexible timing, pay as you go, first demo class free.', 'Personalised online guitar coaching designed for young learners. Every class is one-on-one, paced to your child, and built around songs they love — so motivation stays high while technique builds steadily from the very first note.', 1500.0, 750.0, NULL, 0, 1, 0),
  (10, NULL, 'Online Piano &amp; Keyboard Classes for Kids and Beginners', 'online-piano-amp-keyboard-classes-for-kids-and-beginners', 'Structured 1:1 piano lessons with certified mentors. Learn at your pace, recital-ready.', 'A complete piano journey from first finger placement to confident two-hand playing. Lessons blend technique, theory and the pieces your child wants to play.', 1600.0, 800.0, NULL, 0, 1, 0),
  (11, NULL, 'Python Programming for Kids — Code Your First Projects', 'python-programming-for-kids-code-your-first-projects', 'Project-based live Python classes. Build games and apps from day one.', 'A hands-on introduction to real programming. Learners write actual Python, debug their own code, and finish each level with a project they can show off.', 1800.0, 900.0, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Python-1.jpg', 0, 1, 0),
  (12, NULL, 'Spoken English &amp; Confident Communication', 'spoken-english-amp-confident-communication', 'Live conversational English with personalised feedback. Speak fluently, fearlessly.', 'Move beyond grammar drills to real conversation. Every session is interactive, with structured feedback that targets fluency, pronunciation and confidence.', 1300.0, 650.0, NULL, 0, 1, 0),
  (13, NULL, 'Piano', 'piano', 'Live 1:1 and group Piano classes with expert mentors. Flexible scheduling, first demo free.', '<p>1. Convenience: You can attend classes from the comfort of your own home or any location with internet access. This eliminates the need for commuting, saving you time and money.</p><p>2. Flexibility: Online classes often offer flexible scheduling options, allowing you to choose the time that works best for you. This flexibility is especially beneficial for those with busy schedules or irregular working hours.</p><p>3. Access to Quality Instructors: Online platforms often have a wide selection of qualified instructors from around the world. This means you can find a teacher whose teaching style and expertise align with your learning goals.</p><p>4. Cost-effectiveness: Online classes can be more affordable than in-person lessons since they eliminate overhead costs associated with maintaining a physical location. Additionally, you can often find a variety of pricing options to suit your budget.</p><p>5. Variety of Resources: Online piano classes often come with a variety of supplementary resources such as video tutorials, practice exercises, and interactive learning tools, enhancing the overall learning experience.</p><p>6.Online Certifications: Opt for online examinations through various esteemed institutions and get certified for your skills.</p><p>At IndiaTutorsOnline, we believe that everyone has the potential to unlock their musical talents and start their journey of self-expression. IndiaTutorsOnline provides high-quality, accessible, and engaging online music classes for learners of all ages and skill levels.</p><p>We strive to break down barriers to learning and empower individuals from diverse backgrounds to pursue their passion for music, regardless of their geographical location, financial means, or previous experience.</p>', 600.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Piano-1.jpg', 0, 1, 0),
  (14, NULL, 'Guitar', 'guitar', 'Live 1:1 and group Guitar classes with expert mentors. Flexible scheduling, first demo free.', '<p>At IndiaTutorsOnline, we believe in the limitless potential within everyone to discover and develop their musical talents. We are dedicated to providing high-quality, accessible, and engaging online music classes that cater to learners of all ages and skill levels.</p><p>Our mission is to eliminate barriers to music education, empowering individuals from all walks of life to pursue their passion for music, no matter their location, financial situation, or prior experience.</p><p>Whether your dream is to master the piano, rock out on the guitar, or compose your own symphonies, IndiaTutorsOnline is here to help you bring your musical aspirations to life. Join us today and experience the joy of making music with IndiaTutorsOnline—where your journey to excellence begins.</p>', 600.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Guitar.jpg', 0, 1, 0),
  (15, NULL, 'Ukulele', 'ukulele', 'Live 1:1 and group Ukulele classes with expert mentors. Flexible scheduling, first demo free.', '<p>Accessible Across USA, UK, Europe, Australia, Singapore, Dubai, and More</p><p>Certificates of Completion / Participation Available</p><p>This program develops coordination, rhythm, listening skills, and musical creativity, while building confidence through performance and a love for music.</p><p>👉 Soprano Ukulele is strongly recommended for beginners</p><p>🎵 About Ukulele vs Guitar (Short Understanding)</p><p>The ukulele is a small, four-stringed instrument originally from Hawaii, traditionally strung with nylon strings and tuned G-C-E-A.</p><p>The guitar is a larger six-stringed instrument available in acoustic, classical, and electric variants, with a wider range of tones.</p><p>The ukulele offers a lighter, cheerful tone and is generally easier for young beginners, while the guitar provides a broader tonal range and greater repertoire depth.</p>', 600.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Ukulele.jpg', 0, 1, 0),
  (16, NULL, 'Keyboard', 'keyboard', 'Live 1:1 and group Keyboard classes with expert mentors. Flexible scheduling, first demo free.', '<p>1. Convenience: You can attend classes from the comfort of your own home or any location with internet access. This eliminates the need for commuting, saving you time and money.</p><p>2. Flexibility: Online classes often offer flexible scheduling options, allowing you to choose the time that works best for you. This flexibility is especially beneficial for those with busy schedules or irregular working hours.</p><p>3. Access to Quality Instructors: Online platforms often have a wide selection of qualified instructors from around the world. This means you can find a teacher whose teaching style and expertise align with your learning goals.</p><p>4. Cost-effectiveness: Online classes can be more affordable than in-person lessons since they eliminate overhead costs associated with maintaining a physical location. Additionally, you can often find a variety of pricing options to suit your budget.</p><p>5. Variety of Resources: Online keyboard classes often come with a variety of supplementary resources such as video tutorials, practice exercises, and interactive learning tools, enhancing the overall learning experience.</p><p>6.Online Certifications: Opt for online examinations through various esteemed institutions and get certified for your skills.</p><p>At IndiaTutorsOnline, we believe that everyone has the potential to unlock their musical talents and start their journey of self-expression. IndiaTutorsOnline provides high-quality, accessible, and engaging online music classes for learners of all ages and skill levels.</p><p>We strive to break down barriers to learning and empower individuals from diverse backgrounds to pursue their passion for music, regardless of their geographical location, financial means, or previous experience.</p>', 600.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Keyboard.jpg', 0, 1, 0),
  (17, NULL, 'Drums', 'drums', 'Live 1:1 and group Drums classes with expert mentors. Flexible scheduling, first demo free.', '', 600.0, NULL, NULL, 0, 1, 0),
  (18, NULL, 'Violin', 'violin', 'Live 1:1 and group Violin classes with expert mentors. Flexible scheduling, first demo free.', '', 1000.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Violin.jpg', 0, 1, 0),
  (19, NULL, 'Veena', 'veena', 'Live 1:1 and group Veena classes with expert mentors. Flexible scheduling, first demo free.', '', 600.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Veena.jpg', 0, 1, 0),
  (20, NULL, 'Cello', 'cello', 'Live 1:1 and group Cello classes with expert mentors. Flexible scheduling, first demo free.', '', 1500.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Cello.jpg', 0, 1, 0),
  (21, NULL, 'Viola', 'viola', 'Live 1:1 and group Viola classes with expert mentors. Flexible scheduling, first demo free.', '', 1000.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/AI-Prompting-1.jpg', 0, 1, 0),
  (22, NULL, 'Clarinet', 'clarinet', 'Live 1:1 and group Clarinet classes with expert mentors. Flexible scheduling, first demo free.', '<p>• Learn from home with proper posture and embouchure guidance• Flexible scheduling for students• Access to trained clarinet instructors• Focus on tone production, breath control, and articulation• Preparation for internationally recognized certifications</p><p>For Parents:This program develops breath control, discipline, coordination, listening skills, and musical expression, while building confidence through performance.</p><p>• Standard clarinet used by beginners and professionals• Balanced, warm tone• Widely used in classical, jazz, and band music• Recommended for most students</p><p>• Slightly longer than Bb clarinet• Warmer, darker tone• Common in orchestral repertoire• Used in advanced classical performance</p><p>• Larger instrument with deeper pitch• Rich, resonant sound• Used in orchestras, bands, and modern compositions• Requires more air support</p><p>• Smaller and higher-pitched• Bright, sharp tone• Used in orchestras and wind ensembles• More advanced and less common for beginners</p><p>👉 Bb Clarinet is strongly recommended for beginners</p><p>• Standard learning instrument• Easier fingering system• Comfortable size and handling• Used in ABRSM / Trinity exams</p>', 1500.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/clarinet.png', 0, 1, 0),
  (23, NULL, 'Tabla', 'tabla', 'Live 1:1 and group Tabla classes with expert mentors. Flexible scheduling, first demo free.', '<p>• Interactive and engaging live classes• 1:1 and group sessions available• Accessible globally (India, USA, UK, Europe, etc.)• Flexible scheduling• No contracts or hidden fees• Free demo class• Suitable for kids aged 6+• Focus on Hindustani classical rhythm system• Performance-based learning approach• Certificates of completion available</p><p>• Learn from home with proper hand technique and posture guidance• Flexible scheduling for students• Access to trained Indian classical tabla instructors• Focus on Bol, Taal, Layakari, and rhythmic clarity• Develop timing, coordination, and musical understanding</p><p>This program develops rhythm sense, coordination, discipline, concentration, and mathematical thinking, while enhancing creativity and confidence through structured rhythmic training and performance.</p><p>(Keep same as your file — no change needed)</p><p>The Tabla is the primary percussion instrument in Hindustani classical music, consisting of:</p><p>• Dayan (right drum) – tuned, melodic• Bayan (left drum) – bass, modulation</p><p>It is used in:• Classical music• Semi-classical (Bhajan, Ghazal)• Film &amp; fusion music</p><p>• Hindustani Classical Tradition (Guru-Shishya Parampara)• Institutional frameworks (Prayag Sangeet Samiti / Gandharva Mahavidyalaya)</p>', 600.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Tabla-1.jpg', 0, 1, 0),
  (24, NULL, 'Indian Flute', 'indian-flute', 'Live 1:1 and group Indian Flute classes with expert mentors. Flexible scheduling, first demo free.', '<p>For Parents:This program develops breath control, focus, discipline, and musical sensitivity, while improving cognitive coordination and listening skills.</p><p>What is the difference between Indian Bansuri Flute and Western Concert Flute?</p><p>The Bansuri is a bamboo flute without keys, used mainly in Indian classical music, focusing on expressive playing and improvisation.The Western Concert Flute is a metal, key-based instrument (Boehm system) used in Western classical, orchestral, and modern music.Bansuri relies on breath control and finger placement, while the Western flute allows faster, more precise note changes using keys.The sound of the Bansuri is warm and earthy, whereas the Western flute is bright and versatile.Bansuri learning is largely oral, while Western flute follows structured notation and exams (ABRSM, Trinity).Choose Bansuri for Indian classical expression, and Western flute for global music and certifications.</p><p>At IndiaTutorsOnline, we believe in the limitless potential within everyone to discover and develop their musical talents. We are dedicated to providing high-quality, accessible, and engaging online music classes that cater to learners of all ages and skill levels.</p><p>Our mission is to eliminate barriers to music education, empowering individuals from all walks of life to pursue their passion for music, no matter their location, financial situation, or prior experience.</p><p>Whether your dream is to master the piano, rock out on the Flute, or compose your own symphonies, IndiaTutorsOnline is here to help you bring your musical aspirations to life. Join us today and experience the joy of making music with IndiaTutorsOnline—where your journey to excellence begins.</p>', 600.0, NULL, NULL, 0, 1, 0),
  (25, NULL, 'Western Flute', 'western-flute', 'Live 1:1 and group Western Flute classes with expert mentors. Flexible scheduling, first demo free.', '<p>For Parents:This program develops breath control, focus, discipline, and musical sensitivity, while improving cognitive coordination and listening skills.</p><p>What is the difference between Indian Bansuri Flute and Western Concert Flute?</p><p>The Bansuri is a bamboo flute without keys, used mainly in Indian classical music, focusing on expressive playing and improvisation.The Western Concert Flute is a metal, key-based instrument (Boehm system) used in Western classical, orchestral, and modern music.Bansuri relies on breath control and finger placement, while the Western flute allows faster, more precise note changes using keys.The sound of the Bansuri is warm and earthy, whereas the Western flute is bright and versatile.Bansuri learning is largely oral, while Western flute follows structured notation and exams (ABRSM, Trinity).Choose Bansuri for Indian classical expression, and Western flute for global music and certifications.</p><p>At IndiaTutorsOnline, we believe in the limitless potential within everyone to discover and develop their musical talents. We are dedicated to providing high-quality, accessible, and engaging online music classes that cater to learners of all ages and skill levels.</p><p>Our mission is to eliminate barriers to music education, empowering individuals from all walks of life to pursue their passion for music, no matter their location, financial situation, or prior experience.</p><p>Whether your dream is to master the piano, rock out on the Flute, or compose your own symphonies, IndiaTutorsOnline is here to help you bring your musical aspirations to life. Join us today and experience the joy of making music with IndiaTutorsOnline—where your journey to excellence begins.</p>', 1000.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Sanskrit-1.webp', 0, 1, 0),
  (26, NULL, 'Saxophone', 'saxophone', 'Live 1:1 and group Saxophone classes with expert mentors. Flexible scheduling, first demo free.', '<p>For Parents:This program develops breath control, discipline, coordination, listening skills, and musical expression, while building confidence through performance.</p><p>2. Alto Saxophone (Most Recommended for Beginners)</p><p>👉 Alto Saxophone is strongly recommended for beginners</p><p>What is the difference between Indian Bansuri Flute and Western Concert Flute?</p><p>The Bansuri is a bamboo flute without keys, used mainly in Indian classical music, focusing on expressive playing and improvisation.The Western Concert Flute is a metal, key-based instrument (Boehm system) used in Western classical, orchestral, and modern music.Bansuri relies on breath control and finger placement, while the Western flute allows faster, more precise note changes using keys.The sound of the Bansuri is warm and earthy, whereas the Western flute is bright and versatile.Bansuri learning is largely oral, while Western flute follows structured notation and exams (ABRSM, Trinity).Choose Bansuri for Indian classical expression, and Western flute for global music and certifications.</p><p>At IndiaTutorsOnline, we believe in the limitless potential within everyone to discover and develop their musical talents. We are dedicated to providing high-quality, accessible, and engaging online music classes that cater to learners of all ages and skill levels.</p><p>Our mission is to eliminate barriers to music education, empowering individuals from all walks of life to pursue their passion for music, no matter their location, financial situation, or prior experience.</p><p>Whether your dream is to master the piano, rock out on the Saxophone, or compose your own symphonies, IndiaTutorsOnline is here to help you bring your musical aspirations to life. Join us today and experience the joy of making music with IndiaTutorsOnline—where your journey to excellence begins.</p>', 1000.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Saxophone.jpg', 0, 1, 0),
  (27, NULL, 'Music Theory', 'music-theory', 'Live 1:1 and group Music Theory classes with expert mentors. Flexible scheduling, first demo free.', '<p>1. Convenience: You can attend classes from the comfort of your own home or any location with internet access. This eliminates the need for commuting, saving you time and money.</p><p>2. Flexibility: Online classes often offer flexible scheduling options, allowing you to choose the time that works best for you. This flexibility is especially beneficial for those with busy schedules or irregular working hours.</p><p>3. Access to Quality Instructors: Online platforms often have a wide selection of qualified instructors from around the world. This means you can find a teacher whose teaching style and expertise align with your learning goals.</p><p>4. Cost-effectiveness: Online classes can be more affordable than in-person lessons since they eliminate overhead costs associated with maintaining a physical location. Additionally, you can often find a variety of pricing options to suit your budget.</p><p>5. Variety of Resources: Online music theory classes often come with a variety of supplementary resources such as video tutorials, practice exercises, and interactive learning tools, enhancing the overall learning experience.</p><p>6.Online Certifications: Opt for online examinations through various esteemed institutions and get certified for your skills.</p><p>At IndiaTutorsOnline, we believe that everyone has the potential to unlock their musical talents and start their journey of self-expression. IndiaTutorsOnline provides high-quality, accessible, and engaging online music classes for learners of all ages and skill levels.</p><p>We strive to break down barriers to learning and empower individuals from diverse backgrounds to pursue their passion for music, regardless of their geographical location, financial means, or previous experience.</p>', 600.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/music-theory.jpg.jpeg', 0, 1, 0),
  (28, NULL, 'Trumpet', 'trumpet', 'Live 1:1 and group Trumpet classes with expert mentors. Flexible scheduling, first demo free.', '<p>This program develops breath control, discipline, coordination, listening skills, and musical expression, while building confidence through performance.</p>', 1500.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Trumpet.jpg', 0, 1, 0),
  (29, NULL, 'Sitar', 'sitar', 'Live 1:1 and group Sitar classes with expert mentors. Flexible scheduling, first demo free.', '<p>Indian Classical Sitar Program (Hindustani Tradition)</p><p>Level 1 → Foundation (6–8 months)Level 2 → Raga Development &amp; Technique (6–8 months)Level 3 → Advanced Performance &amp; Mastery (8–12 months)</p><p>• Live online classes (1:1 or group)• Weekly structured sessions• Guided riyaz (practice routines)• Assignment-based progression• Periodic performance reviews• Feedback-driven learning• Optional certification pathway</p><p>This program develops concentration, finger dexterity, disciplined practice, tonal awareness, and cultural appreciation, while enhancing creativity and confidence through structured melodic training and performance.</p><p>(Keep same as your file — no change needed)</p><p>The Sitar is one of the most iconic string instruments in Hindustani classical music, renowned globally for its rich, resonant tone and versatility. The Sitar consists of:</p><p>🎓 Hindustani Classical Tradition (Guru–Shishya Parampara)</p><p>This is the traditional way of learning Indian classical music, where the student learns directly from a Guru (master) through:</p>', 600.0, NULL, NULL, 0, 1, 0),
  (30, NULL, 'Recorder', 'recorder', 'Live 1:1 and group Recorder classes with expert mentors. Flexible scheduling, first demo free.', '', 600.0, NULL, NULL, 0, 1, 0);

INSERT INTO `courses` (`id`, `sku`, `name`, `slug`, `short_description`, `description`, `regular_price`, `sale_price`, `image_url`, `is_featured`, `is_published`, `position`) VALUES
  (31, NULL, 'Carnatic Violin', 'carnatic-violin', 'Live 1:1 and group Carnatic Violin classes with expert mentors. Flexible scheduling, first demo free.', '', 1000.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Carnatic-3.jpg', 0, 1, 0),
  (32, NULL, 'Carnatic Vocal Music', 'carnatic-vocal-music', 'Live 1:1 and group Carnatic Vocal Music classes with expert mentors. Flexible scheduling, first demo free.', '<p>Carnatic vocal music is a classical tradition originating from South India, characterized by its emphasis on intricate melodies, rhythmic precision, and devotional themes. In this art form, vocalists play a central role, rendering compositions that follow specific ragas and talas. The music often carries spiritual depth and cultural significance, making Carnatic vocal music a revered classical genre.</p><p>Start learning Carnatic Vocal Music from the comfort of your home!</p><p>Why Choose Online Carnatic Vocal Music Classes?</p><p>Rich Cultural Heritage: Carnatic vocal music is deeply embedded in the cultural fabric of South India, carrying centuries-old traditions and spiritual depth. Choosing this genre allows you to connect with a profound cultural heritage.</p><p>Melodic Complexity: The intricate melodic patterns of Carnatic music, expressed through a vast array of ragas, provide a unique and challenging musical journey. Learning to navigate these melodies enhances your understanding of musical intricacies.</p><p>Spiritual and Devotional Essence: Many Carnatic compositions carry devotional and spiritual themes, offering a transcendent and emotional musical experience. Engaging with these compositions allows you to explore the spiritual dimensions of music.</p><p>Rhythmic Precision: Carnatic music places a strong emphasis on rhythmic precision through talas. Mastering the rhythmic intricacies contributes to a well-rounded musical education, fostering a sense of discipline and control.</p><p>Vocal Expression: Carnatic vocal music places the human voice at the forefront, allowing for nuanced expression and emotional depth. Choosing to specialize in vocal music enables you to convey intricate musical nuances with your voice.</p>', 600.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Carnatic-4.jpg', 0, 1, 0),
  (33, NULL, 'Hindustani Vocal Music', 'hindustani-vocal-music', 'Live 1:1 and group Hindustani Vocal Music classes with expert mentors. Flexible scheduling, first demo free.', '<p>Hindustani vocal music, a classical tradition originating in the Indian subcontinent, is characterized by its emphasis on improvisation, intricate melodic patterns, and the use of ragas and talas. The genre&#x27;s rich history involves contributions from various musicians and scholars, with a profound connection between performers and audiences. In Hindustani vocal music, artists express deep emotions and narratives through their voices, employing techniques such as ornamentation and vibrato. The diverse repertoire spans devotional, classical, semi-classical, and experimental compositions. Gharanas, distinct musical schools, have played a significant role in shaping the tradition.</p><p>Start learning Hindustani Vocal Music from the comfort of your home!</p><p>Why Choose Online Hindustani Vocal Music Classes?</p><p>Expert Instructors: We have a team of experienced and talented vocal instructors who are master’s degree holders in Hindustani music or equivalent and are dedicated to helping you develop your vocal skills and achieve your musical goals. They possess a deep understanding of Hindustani vocal music and are passionate about sharing their knowledge with students.</p><p>Cultural Connection: Hindustani vocal music is deeply rooted in Indian culture and heritage, offering learners a profound connection to centuries-old traditions and artistic expressions.</p><p>Artistic Expression: Hindustani vocal music provides a platform for creative self-expression through melody, rhythm, and emotion, allowing learners to explore their artistic potential and develop their unique voice.</p><p>Musical Proficiency: Hindustani vocal training equips learners with essential musical skills such as pitch control, breath control, voice modulation, and improvisation, enhancing overall vocal proficiency and musicianship.</p><p>Emotional Intelligence: Engaging with Hindustani music fosters emotional intelligence as learners delve into the evocative expressions of different ragas and compositions, deepening their understanding of human emotions and cultural nuances.</p>', 600.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Hindustani-Vocal.jpg.jpeg', 0, 1, 0),
  (34, NULL, 'Western Vocal Music', 'western-vocal-music', 'Live 1:1 and group Western Vocal Music classes with expert mentors. Flexible scheduling, first demo free.', '<p>Why Choose Online Western Vocal Music Classes?</p><p>Expert Instructors: We have a team of experienced and talented vocal instructors who are certified from Trinity College London/Associated Board of the Royal Schools of Music/Rockschool or equivalent, who are dedicated to helping you develop your vocal skills and achieve your musical goals. They possess a deep understanding of Western vocal techniques and are passionate about sharing their knowledge with students.</p><p>Flexible Learning: With our online classes, you can enjoy the convenience of learning from the comfort of your own home, at your own pace. We offer flexible scheduling options to accommodate your busy lifestyle, allowing you to pursue your passion for music without disrupting your daily routine.</p><p>Comprehensive Curriculum: Our curriculum is carefully crafted to provide a well-rounded education in Western vocal music. Through our coaching students can apply for certifications from Trinity College London/Associated Board of the Royal Schools of Music/Rockschool. From vocal warm-ups and breathing exercises to exploring various musical genres and styles, our classes cover a wide range of topics to enhance your vocal abilities and musical understanding.</p><p>Personalized Approach: We understand that every student is unique, with different learning styles and goals. That&#x27;s why our instructors tailor their teaching methods to meet your individual needs and coach you for the certification of your choice. Whether you&#x27;re interested in pop, rock, jazz, or classical music, we&#x27;ll help you develop a versatile voice that can adapt to any genre.</p><p>Affordable Pricing: We believe that high-quality music education should be accessible to everyone. That&#x27;s why we offer competitive pricing options that fit various budgets. We are committed to providing exceptional value for your investment in your musical journey.</p><p>Enhanced Academic Performance: Studies have shown a positive correlation between music education and academic performance. Learning to sing involves various cognitive skills such as memory, attention, and pattern recognition, which can contribute to improved academic abilities.</p><p>Improved Discipline and Time Management: Committing to regular online classes fosters discipline and time management skills. These qualities are transferable to academic pursuits, helping children develop effective study habits and meet deadlines.</p>', 600.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Western-Music-.jpg.jpeg', 0, 1, 0),
  (35, NULL, 'Scratch', 'scratch', 'Live 1:1 and group Scratch classes with expert mentors. Flexible scheduling, first demo free.', '', 300.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Scratch.jpg', 0, 1, 0),
  (36, NULL, 'Blockly', 'blockly', 'Live 1:1 and group Blockly classes with expert mentors. Flexible scheduling, first demo free.', '', 300.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Blockly.jpg', 0, 1, 0),
  (37, NULL, 'Roblox & Minecraft', 'roblox-minecraft', 'Live 1:1 and group Roblox & Minecraft classes with expert mentors. Flexible scheduling, first demo free.', '', 300.0, NULL, NULL, 0, 1, 0),
  (38, NULL, 'Python', 'python', 'Live 1:1 and group Python classes with expert mentors. Flexible scheduling, first demo free.', '', 300.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Python.jpg', 0, 1, 0),
  (39, NULL, 'Java', 'java', 'Live 1:1 and group Java classes with expert mentors. Flexible scheduling, first demo free.', '', 425.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/JAva.jpg', 0, 1, 0),
  (40, NULL, 'C++', 'c', 'Live 1:1 and group C++ classes with expert mentors. Flexible scheduling, first demo free.', '', 300.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/content-writing-course1s-1.jpg', 0, 1, 0),
  (41, NULL, 'Web Development', 'web-development', 'Live 1:1 and group Web Development classes with expert mentors. Flexible scheduling, first demo free.', '', 300.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Web-Developement.jpg', 0, 1, 0),
  (42, NULL, 'MIT App Inventor', 'mit-app-inventor', 'Live 1:1 and group MIT App Inventor classes with expert mentors. Flexible scheduling, first demo free.', '', 300.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/App-Developement-29.jpg', 0, 1, 0),
  (43, NULL, 'Robotics', 'robotics', 'Live 1:1 and group Robotics classes with expert mentors. Flexible scheduling, first demo free.', '', 300.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Robotics.jpg', 0, 1, 0),
  (44, NULL, 'AI & ML', 'ai-ml', 'Live 1:1 and group AI & ML classes with expert mentors. Flexible scheduling, first demo free.', '', 600.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/AIML.jpg', 0, 1, 0),
  (45, NULL, 'Data Science', 'data-science', 'Live 1:1 and group Data Science classes with expert mentors. Flexible scheduling, first demo free.', '', 450.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Data-Science.jpg', 0, 1, 0),
  (46, NULL, 'AI Prompting', 'ai-prompting', 'Live 1:1 and group AI Prompting classes with expert mentors. Flexible scheduling, first demo free.', '', 300.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/AI-Prompting.jpg', 0, 1, 0),
  (47, NULL, 'Graphics Design', 'graphics-design', 'Live 1:1 and group Graphics Design classes with expert mentors. Flexible scheduling, first demo free.', '', 300.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Graphics-Design.jpg', 0, 1, 0),
  (48, NULL, 'Video Editing', 'video-editing', 'Live 1:1 and group Video Editing classes with expert mentors. Flexible scheduling, first demo free.', '', 450.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Video-Editing.jpg', 0, 1, 0),
  (49, NULL, 'Animation', 'animation', 'Live 1:1 and group Animation classes with expert mentors. Flexible scheduling, first demo free.', '', 450.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Animation.jpg', 0, 1, 0),
  (50, NULL, 'VFX', 'vfx', 'Live 1:1 and group VFX classes with expert mentors. Flexible scheduling, first demo free.', '', 300.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/VFX.jpg.jpeg', 0, 1, 0),
  (51, NULL, 'AWS', 'aws', 'Live 1:1 and group AWS classes with expert mentors. Flexible scheduling, first demo free.', '', 450.0, NULL, NULL, 0, 1, 0),
  (52, NULL, 'DevOps', 'devops', 'Live 1:1 and group DevOps classes with expert mentors. Flexible scheduling, first demo free.', '', 450.0, NULL, NULL, 0, 1, 0),
  (53, NULL, 'Rubik''s Cube', 'rubik-s-cube', 'Live 1:1 and group Rubik''s Cube classes with expert mentors. Flexible scheduling, first demo free.', '', 300.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Rubik-pixabay-54101.png', 0, 1, 0),
  (54, NULL, 'Chess', 'chess', 'Live 1:1 and group Chess classes with expert mentors. Flexible scheduling, first demo free.', '', 300.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Chess.jpg', 0, 1, 0),
  (55, NULL, 'Arts & Painting', 'arts-painting', 'Live 1:1 and group Arts & Painting classes with expert mentors. Flexible scheduling, first demo free.', '<p>Why Choose Online Arts and Painting Classes?</p><p>In a world where screens dominate our daily lives, it&#x27;s no surprise that the realm of education has also shifted its focus to the digital sphere. Online learning platforms have revolutionized how we acquire new skills, and the realm of arts and painting is no exception. Whether you&#x27;re a seasoned artist or an eager beginner, the benefits of enrolling in online arts and painting classes are boundless. Here&#x27;s why you should consider embracing the virtual canvas:</p>', 200.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Arts-And-Painting-1.jpg', 0, 1, 0),
  (56, NULL, 'Creative Writing', 'creative-writing', 'Live 1:1 and group Creative Writing classes with expert mentors. Flexible scheduling, first demo free.', '', 300.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/content-writing-course1s.jpg', 0, 1, 0),
  (57, NULL, 'Public Speaking', 'public-speaking', 'Live 1:1 and group Public Speaking classes with expert mentors. Flexible scheduling, first demo free.', '<p>Online Public Speaking – Trial Class Plan (Session 1)</p><p>Duration: 60–75 MinutesMode: Online (Teacher + 5 Students)Theme: Introduction to Public Speaking &amp; SWOT-Based Speaking Activity</p><p>Objective: Make students comfortable and start speaking immediately.</p><p>“When you hear the words Public Speaking, what comes to your mind?”</p><p>2. What Exactly is Public Speaking? (8–10 minutes)</p><p>Public Speaking is the ability to speak clearly, confidently, and effectively in front of an audience with the purpose of:</p><p>It is not only about talking. It is about:✅ Confidence✅ Clear thoughts✅ Strong body language✅ Knowing your audience✅ Structuring your ideas✅ Using voice effectively</p><p>Public speaking is a life skill. It helps in:</p>', 150.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Public-Speaking.jpg', 0, 1, 0),
  (58, NULL, 'Spelling Competition', 'spelling-competition', 'Live 1:1 and group Spelling Competition classes with expert mentors. Flexible scheduling, first demo free.', '', 300.0, NULL, NULL, 0, 1, 0),
  (59, NULL, 'Bollywood Dance', 'bollywood-dance', 'Live 1:1 and group Bollywood Dance classes with expert mentors. Flexible scheduling, first demo free.', '', 300.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Bollywood.jpg', 0, 1, 0),
  (60, NULL, 'Kuchipudi Dance', 'kuchipudi-dance', 'Live 1:1 and group Kuchipudi Dance classes with expert mentors. Flexible scheduling, first demo free.', '', 300.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Kuchipudi.jpg', 0, 1, 0);

INSERT INTO `courses` (`id`, `sku`, `name`, `slug`, `short_description`, `description`, `regular_price`, `sale_price`, `image_url`, `is_featured`, `is_published`, `position`) VALUES
  (61, NULL, 'Bharatnatyam Dance', 'bharatnatyam-dance', 'Live 1:1 and group Bharatnatyam Dance classes with expert mentors. Flexible scheduling, first demo free.', '', 300.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Bharatnatyam.jpg.jpeg', 0, 1, 0),
  (62, NULL, 'Kathak Dance', 'kathak-dance', 'Live 1:1 and group Kathak Dance classes with expert mentors. Flexible scheduling, first demo free.', '', 300.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Kathak.jpg', 0, 1, 0),
  (63, NULL, 'Hip Hop Dance', 'hip-hop-dance', 'Live 1:1 and group Hip Hop Dance classes with expert mentors. Flexible scheduling, first demo free.', '', 300.0, NULL, NULL, 0, 1, 0),
  (64, NULL, 'Zumba Dance', 'zumba-dance', 'Live 1:1 and group Zumba Dance classes with expert mentors. Flexible scheduling, first demo free.', '', 300.0, NULL, NULL, 0, 1, 0),
  (65, NULL, 'Western Dance Dance', 'western-dance-dance', 'Live 1:1 and group Western Dance Dance classes with expert mentors. Flexible scheduling, first demo free.', '', 300.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Sanskrit.webp', 0, 1, 0),
  (66, NULL, 'Spanish', 'spanish', 'Live 1:1 and group Spanish classes with expert mentors. Flexible scheduling, first demo free.', '', 300.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Spanish.jpg', 0, 1, 0),
  (67, NULL, 'French', 'french', 'Live 1:1 and group French classes with expert mentors. Flexible scheduling, first demo free.', '', 300.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/French.jpg', 0, 1, 0),
  (68, NULL, 'German', 'german', 'Live 1:1 and group German classes with expert mentors. Flexible scheduling, first demo free.', '', 300.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/German.jpg', 0, 1, 0),
  (69, NULL, 'Mandarin', 'mandarin', 'Live 1:1 and group Mandarin classes with expert mentors. Flexible scheduling, first demo free.', '', 300.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Mandarin.jpg', 0, 1, 0),
  (70, NULL, 'Russian', 'russian', 'Live 1:1 and group Russian classes with expert mentors. Flexible scheduling, first demo free.', '', 300.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Russian.jpg', 0, 1, 0),
  (71, NULL, 'Sanskrit', 'sanskrit', 'Live 1:1 and group Sanskrit classes with expert mentors. Flexible scheduling, first demo free.', '', 300.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Sanskrit.jpg', 0, 1, 0),
  (72, NULL, 'Hindi', 'hindi', 'Live 1:1 and group Hindi classes with expert mentors. Flexible scheduling, first demo free.', '', 300.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Hindi.jpg', 0, 1, 0),
  (73, NULL, 'Tamil', 'tamil', 'Live 1:1 and group Tamil classes with expert mentors. Flexible scheduling, first demo free.', '', 300.0, NULL, NULL, 0, 1, 0),
  (74, NULL, 'Telugu', 'telugu', 'Live 1:1 and group Telugu classes with expert mentors. Flexible scheduling, first demo free.', '', 300.0, NULL, NULL, 0, 1, 0),
  (75, NULL, 'Kannada', 'kannada', 'Live 1:1 and group Kannada classes with expert mentors. Flexible scheduling, first demo free.', '', 300.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Kannada.jpg', 0, 1, 0),
  (76, NULL, 'Malayalam', 'malayalam', 'Live 1:1 and group Malayalam classes with expert mentors. Flexible scheduling, first demo free.', '', 300.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Malayalam.jpg', 0, 1, 0),
  (77, NULL, 'Phonics, Numbers & Language Development', 'phonics-numbers-language-development', 'Live 1:1 and group Phonics, Numbers & Language Development classes with expert mentors. Flexible scheduling, first demo free.', '', 600.0, NULL, NULL, 0, 1, 0),
  (78, NULL, 'Mathematics Grade 1-7', 'mathematics-grade-1-7', 'Live 1:1 and group Mathematics Grade 1-7 classes with expert mentors. Flexible scheduling, first demo free.', '', 600.0, NULL, NULL, 0, 1, 0),
  (79, NULL, 'Mathematics Grade 8', 'mathematics-grade-8', 'Live 1:1 and group Mathematics Grade 8 classes with expert mentors. Flexible scheduling, first demo free.', '', 750.0, NULL, NULL, 0, 1, 0),
  (80, NULL, 'Vedic Maths (Grade 3-6)', 'vedic-maths-grade-3-6', 'Live 1:1 and group Vedic Maths (Grade 3-6) classes with expert mentors. Flexible scheduling, first demo free.', '', 600.0, NULL, NULL, 0, 1, 0),
  (81, NULL, 'Vedic Maths (Advanced)', 'vedic-maths-advanced', 'Live 1:1 and group Vedic Maths (Advanced) classes with expert mentors. Flexible scheduling, first demo free.', '', 1000.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Vedic-Math.jpg', 0, 1, 0),
  (82, NULL, 'English Grade 1-7', 'english-grade-1-7', 'Live 1:1 and group English Grade 1-7 classes with expert mentors. Flexible scheduling, first demo free.', '', 600.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/English-8.jpg', 0, 1, 0),
  (83, NULL, 'English Grade 8', 'english-grade-8', 'Live 1:1 and group English Grade 8 classes with expert mentors. Flexible scheduling, first demo free.', '', 750.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/English-9.jpg', 0, 1, 0),
  (84, NULL, 'Science Grade 1-7', 'science-grade-1-7', 'Live 1:1 and group Science Grade 1-7 classes with expert mentors. Flexible scheduling, first demo free.', '', 600.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Kids-Science-1.jpg', 0, 1, 0),
  (85, NULL, 'Science Grade 8', 'science-grade-8', 'Live 1:1 and group Science Grade 8 classes with expert mentors. Flexible scheduling, first demo free.', '', 750.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Kids-Science-2.jpg', 0, 1, 0),
  (86, NULL, 'Social Studies Grade 1-7', 'social-studies-grade-1-7', 'Live 1:1 and group Social Studies Grade 1-7 classes with expert mentors. Flexible scheduling, first demo free.', '', 600.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Social-Studies-.jpg-3.jpeg', 0, 1, 0),
  (87, NULL, 'Social Studies Grade 8', 'social-studies-grade-8', 'Live 1:1 and group Social Studies Grade 8 classes with expert mentors. Flexible scheduling, first demo free.', '', 750.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Social-Studies-.jpg-2.jpeg', 0, 1, 0),
  (88, NULL, 'Abacus', 'abacus', 'Live 1:1 and group Abacus classes with expert mentors. Flexible scheduling, first demo free.', '', 600.0, NULL, NULL, 0, 1, 0),
  (89, NULL, 'Mathematics Grade 9-10', 'mathematics-grade-9-10', 'Live 1:1 and group Mathematics Grade 9-10 classes with expert mentors. Flexible scheduling, first demo free.', '', 1000.0, NULL, NULL, 0, 1, 0),
  (90, NULL, 'Mathematics Grade 11-12', 'mathematics-grade-11-12', 'Live 1:1 and group Mathematics Grade 11-12 classes with expert mentors. Flexible scheduling, first demo free.', '', 1200.0, NULL, NULL, 0, 1, 0);

INSERT INTO `courses` (`id`, `sku`, `name`, `slug`, `short_description`, `description`, `regular_price`, `sale_price`, `image_url`, `is_featured`, `is_published`, `position`) VALUES
  (91, NULL, 'English Grade 9-10', 'english-grade-9-10', 'Live 1:1 and group English Grade 9-10 classes with expert mentors. Flexible scheduling, first demo free.', '', 1000.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/English-6.jpg', 0, 1, 0),
  (92, NULL, 'English Grade 11-12', 'english-grade-11-12', 'Live 1:1 and group English Grade 11-12 classes with expert mentors. Flexible scheduling, first demo free.', '', 1200.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/English-7.jpg', 0, 1, 0),
  (93, NULL, 'Science Grade 9-10', 'science-grade-9-10', 'Live 1:1 and group Science Grade 9-10 classes with expert mentors. Flexible scheduling, first demo free.', '', 1000.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Kids-Science.jpg', 0, 1, 0),
  (94, NULL, 'Physics Grade 11-12', 'physics-grade-11-12', 'Live 1:1 and group Physics Grade 11-12 classes with expert mentors. Flexible scheduling, first demo free.', '', 1200.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Physics.jpg.jpeg', 0, 1, 0),
  (95, NULL, 'Chemistry Grade 11-12', 'chemistry-grade-11-12', 'Live 1:1 and group Chemistry Grade 11-12 classes with expert mentors. Flexible scheduling, first demo free.', '', 1200.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/AP-Chemistry.jpg', 0, 1, 0),
  (96, NULL, 'Biology Grade 11-12', 'biology-grade-11-12', 'Live 1:1 and group Biology Grade 11-12 classes with expert mentors. Flexible scheduling, first demo free.', '', 1200.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Biology.jpg', 0, 1, 0),
  (97, NULL, 'Social Studies Grade 9-10', 'social-studies-grade-9-10', 'Live 1:1 and group Social Studies Grade 9-10 classes with expert mentors. Flexible scheduling, first demo free.', '', 1000.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Social-Studies-.jpg.jpeg', 0, 1, 0),
  (98, NULL, 'Social Studies Grade 11-12', 'social-studies-grade-11-12', 'Live 1:1 and group Social Studies Grade 11-12 classes with expert mentors. Flexible scheduling, first demo free.', '', 1200.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Social-Studies-.jpg-1.jpeg', 0, 1, 0),
  (99, NULL, 'Integrated Math I/II/III', 'integrated-math-i-ii-iii', 'Live 1:1 and group Integrated Math I/II/III classes with expert mentors. Flexible scheduling, first demo free.', '', 1200.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Integeated-Math.jpg', 0, 1, 0),
  (100, NULL, 'Algebra I', 'algebra-i', 'Live 1:1 and group Algebra I classes with expert mentors. Flexible scheduling, first demo free.', '', 1200.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Untitled-design-73.png', 0, 1, 0),
  (101, NULL, 'Algebra II', 'algebra-ii', 'Live 1:1 and group Algebra II classes with expert mentors. Flexible scheduling, first demo free.', '', 1200.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/11ae09ff89924f31a22bcef65cf1326c119f6d9abd6bb437a7271b84a7c7623f.jpg', 0, 1, 0),
  (102, NULL, 'Geometry', 'geometry', 'Live 1:1 and group Geometry classes with expert mentors. Flexible scheduling, first demo free.', '', 1200.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/drum.jpg', 0, 1, 0),
  (103, NULL, 'Pre-Calculus', 'pre-calculus', 'Live 1:1 and group Pre-Calculus classes with expert mentors. Flexible scheduling, first demo free.', '', 1200.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Pre-Calculus.jpg', 0, 1, 0),
  (104, NULL, 'Calculus', 'calculus', 'Live 1:1 and group Calculus classes with expert mentors. Flexible scheduling, first demo free.', '', 1200.0, NULL, NULL, 0, 1, 0),
  (105, NULL, 'Essay Writing', 'essay-writing', 'Live 1:1 and group Essay Writing classes with expert mentors. Flexible scheduling, first demo free.', '', 1000.0, NULL, NULL, 0, 1, 0),
  (106, NULL, 'Economics', 'economics', 'Live 1:1 and group Economics classes with expert mentors. Flexible scheduling, first demo free.', '', 1200.0, NULL, NULL, 0, 1, 0),
  (107, NULL, 'Honors Chemistry', 'honors-chemistry', 'Live 1:1 and group Honors Chemistry classes with expert mentors. Flexible scheduling, first demo free.', '', 1000.0, NULL, NULL, 0, 1, 0),
  (108, NULL, 'Honors Biology', 'honors-biology', 'Live 1:1 and group Honors Biology classes with expert mentors. Flexible scheduling, first demo free.', '', 1000.0, NULL, NULL, 0, 1, 0),
  (109, NULL, 'Honors Physics', 'honors-physics', 'Live 1:1 and group Honors Physics classes with expert mentors. Flexible scheduling, first demo free.', '', 1000.0, NULL, NULL, 0, 1, 0),
  (110, NULL, 'AP Physics 1/2', 'ap-physics-1-2', 'Live 1:1 and group AP Physics 1/2 classes with expert mentors. Flexible scheduling, first demo free.', '', 1200.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/App-Developement-13.jpg', 0, 1, 0),
  (111, NULL, 'AP Physics C', 'ap-physics-c', 'Live 1:1 and group AP Physics C classes with expert mentors. Flexible scheduling, first demo free.', '', 1500.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/App-Developement-14.jpg', 0, 1, 0),
  (112, NULL, 'AP Physics C Mechanics', 'ap-physics-c-mechanics', 'Live 1:1 and group AP Physics C Mechanics classes with expert mentors. Flexible scheduling, first demo free.', '', 1500.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/App-Developement-19.jpg', 0, 1, 0),
  (113, NULL, 'AP Chemistry', 'ap-chemistry', 'Live 1:1 and group AP Chemistry classes with expert mentors. Flexible scheduling, first demo free.', '', 1200.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/AP-Chemistry.png', 0, 1, 0),
  (114, NULL, 'AP Biology', 'ap-biology', 'Live 1:1 and group AP Biology classes with expert mentors. Flexible scheduling, first demo free.', '', 1200.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/AP-Biology-1.png', 0, 1, 0),
  (115, NULL, 'AP Pre-Calculus', 'ap-pre-calculus', 'Live 1:1 and group AP Pre-Calculus classes with expert mentors. Flexible scheduling, first demo free.', '', 1200.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/App-Developement-24.jpg', 0, 1, 0),
  (116, NULL, 'AP Calculus AB', 'ap-calculus-ab', 'Live 1:1 and group AP Calculus AB classes with expert mentors. Flexible scheduling, first demo free.', '', 1500.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/App-Developement-25.jpg', 0, 1, 0),
  (117, NULL, 'AP Calculus BC', 'ap-calculus-bc', 'Live 1:1 and group AP Calculus BC classes with expert mentors. Flexible scheduling, first demo free.', '', 1500.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/App-Developement-26.jpg', 0, 1, 0),
  (118, NULL, 'AP English Language', 'ap-english-language', 'Live 1:1 and group AP English Language classes with expert mentors. Flexible scheduling, first demo free.', '', 1200.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/App-Developement-28.jpg', 0, 1, 0),
  (119, NULL, 'AP Spanish', 'ap-spanish', 'Live 1:1 and group AP Spanish classes with expert mentors. Flexible scheduling, first demo free.', '', 1000.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/AP-Calculus-AB-BC-2.png', 0, 1, 0),
  (120, NULL, 'AP French', 'ap-french', 'Live 1:1 and group AP French classes with expert mentors. Flexible scheduling, first demo free.', '', 1000.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/AP-Calculus-AB-BC-4.png', 0, 1, 0);

INSERT INTO `courses` (`id`, `sku`, `name`, `slug`, `short_description`, `description`, `regular_price`, `sale_price`, `image_url`, `is_featured`, `is_published`, `position`) VALUES
  (121, NULL, 'AP Computer Science', 'ap-computer-science', 'Live 1:1 and group AP Computer Science classes with expert mentors. Flexible scheduling, first demo free.', '', 1000.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/AP-Computer-Science.png', 0, 1, 0),
  (122, NULL, 'AP Computer Science Principles', 'ap-computer-science-principles', 'Live 1:1 and group AP Computer Science Principles classes with expert mentors. Flexible scheduling, first demo free.', '', 1000.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/AP-Computer-Science-Principles-2.png', 0, 1, 0),
  (123, NULL, 'AP US History', 'ap-us-history', 'Live 1:1 and group AP US History classes with expert mentors. Flexible scheduling, first demo free.', '', 1000.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/App-Developement-12.jpg', 0, 1, 0),
  (124, NULL, 'AP European History', 'ap-european-history', 'Live 1:1 and group AP European History classes with expert mentors. Flexible scheduling, first demo free.', '', 1000.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/App-Developement-3.jpg', 0, 1, 0),
  (125, NULL, 'AP Statistics', 'ap-statistics', 'Live 1:1 and group AP Statistics classes with expert mentors. Flexible scheduling, first demo free.', '', 1500.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/App-Developement-5.jpg', 0, 1, 0),
  (126, NULL, 'AP Music Theory', 'ap-music-theory', 'Live 1:1 and group AP Music Theory classes with expert mentors. Flexible scheduling, first demo free.', '', 1000.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/App-Developement-8.jpg', 0, 1, 0),
  (127, NULL, 'AP Micro Economics', 'ap-micro-economics', 'Live 1:1 and group AP Micro Economics classes with expert mentors. Flexible scheduling, first demo free.', '', 1000.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/App-Developement.jpg', 0, 1, 0),
  (128, NULL, 'AP Macro Economics', 'ap-macro-economics', 'Live 1:1 and group AP Macro Economics classes with expert mentors. Flexible scheduling, first demo free.', '', 1000.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/App-Developement-1.jpg', 0, 1, 0),
  (129, NULL, 'English SAT/PSAT', 'english-sat-psat', 'Live 1:1 and group English SAT/PSAT classes with expert mentors. Flexible scheduling, first demo free.', '', 1200.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/English-2.jpg', 0, 1, 0),
  (130, NULL, 'Math SAT/PSAT', 'math-sat-psat', 'Live 1:1 and group Math SAT/PSAT classes with expert mentors. Flexible scheduling, first demo free.', '', 1200.0, NULL, 'https://indiatutorsonline.com/wp-content/uploads/2026/05/Carnatic-2.jpg', 0, 1, 0),
  (131, NULL, 'NMSQT', 'nmsqt', 'Live 1:1 and group NMSQT classes with expert mentors. Flexible scheduling, first demo free.', '', 1200.0, NULL, NULL, 0, 1, 0),
  (132, NULL, 'ACT', 'act', 'Live 1:1 and group ACT classes with expert mentors. Flexible scheduling, first demo free.', '', 1200.0, NULL, NULL, 0, 1, 0),
  (133, NULL, 'Art and Craft', 'art-and-craft', 'Live one-to-one and group Art and Craft classes with expert mentors. Flexible scheduling, first demo free.', '', 200.0, NULL, NULL, 0, 1, 0),
  (134, NULL, 'Digital SAT/PSAT Math', 'digital-sat-psat-math', 'Live one-to-one and group Digital SAT/PSAT Math classes with expert mentors. Flexible scheduling, first demo free.', '', 1200.0, NULL, NULL, 0, 1, 0);

-- ================================================================
-- DATA: 260 category_course links
-- ================================================================

INSERT INTO `category_course` (`category_id`, `course_id`) VALUES
  (1, 1),
  (1, 2),
  (1, 3),
  (2, 4),
  (3, 5),
  (4, 6),
  (5, 7),
  (6, 8),
  (4, 9),
  (7, 9),
  (8, 10),
  (4, 10),
  (9, 11),
  (10, 11),
  (11, 12),
  (12, 12),
  (8, 13),
  (13, 13),
  (13, 14),
  (7, 14),
  (13, 15),
  (14, 15),
  (13, 16),
  (15, 16),
  (16, 17),
  (13, 17),
  (17, 18),
  (13, 18),
  (18, 19),
  (13, 19),
  (19, 20),
  (13, 20),
  (20, 21),
  (13, 21),
  (13, 22),
  (21, 22),
  (13, 23),
  (22, 23),
  (13, 24),
  (23, 24),
  (24, 25),
  (13, 25),
  (25, 26),
  (13, 26),
  (26, 27),
  (13, 27),
  (27, 28),
  (13, 28),
  (28, 29),
  (13, 29),
  (29, 30),
  (13, 30),
  (13, 31),
  (30, 31),
  (32, 32),
  (31, 32),
  (33, 33),
  (31, 33),
  (34, 34),
  (31, 34),
  (35, 35),
  (36, 35),
  (35, 36),
  (37, 36),
  (35, 37),
  (38, 37),
  (10, 38),
  (35, 38),
  (35, 39),
  (39, 39),
  (40, 40),
  (35, 40),
  (41, 41),
  (35, 41),
  (42, 42),
  (35, 42),
  (43, 43),
  (35, 43),
  (35, 44),
  (44, 44),
  (35, 45),
  (45, 45),
  (35, 46),
  (46, 46),
  (35, 47),
  (47, 47),
  (48, 48),
  (35, 48),
  (49, 49),
  (35, 49),
  (50, 50),
  (35, 50),
  (35, 51),
  (51, 51),
  (35, 52),
  (52, 52),
  (3, 53),
  (53, 53),
  (3, 54),
  (54, 54),
  (56, 55),
  (55, 55),
  (57, 56),
  (55, 56),
  (58, 57),
  (55, 57),
  (59, 58),
  (55, 58),
  (60, 59),
  (61, 59),
  (60, 60),
  (62, 60),
  (60, 61),
  (63, 61),
  (64, 62),
  (60, 62),
  (65, 63),
  (60, 63),
  (66, 64),
  (60, 64),
  (67, 65),
  (60, 65),
  (11, 66),
  (68, 66),
  (11, 67),
  (69, 67),
  (11, 68),
  (70, 68),
  (11, 69),
  (71, 69),
  (72, 70),
  (11, 70),
  (73, 71),
  (11, 71),
  (74, 72),
  (11, 72),
  (75, 73),
  (11, 73),
  (11, 74),
  (76, 74),
  (11, 75),
  (77, 75),
  (11, 76),
  (78, 76),
  (80, 77),
  (79, 77),
  (81, 78),
  (79, 78),
  (81, 79),
  (79, 79),
  (82, 80),
  (79, 80),
  (82, 81),
  (79, 81),
  (83, 82),
  (79, 82),
  (83, 83),
  (79, 83),
  (84, 84),
  (79, 84),
  (84, 85),
  (79, 85),
  (85, 86),
  (79, 86),
  (85, 87),
  (79, 87),
  (86, 88),
  (79, 88),
  (81, 89),
  (87, 89),
  (81, 90),
  (87, 90),
  (83, 91),
  (87, 91),
  (83, 92),
  (87, 92),
  (84, 93),
  (87, 93),
  (88, 94),
  (87, 94),
  (89, 95),
  (87, 95),
  (90, 96),
  (87, 96),
  (85, 97),
  (87, 97),
  (85, 98),
  (87, 98),
  (81, 99),
  (87, 99),
  (91, 100),
  (87, 100),
  (91, 101),
  (87, 101),
  (92, 102),
  (87, 102),
  (93, 103),
  (87, 103),
  (93, 104),
  (87, 104),
  (94, 105),
  (87, 105),
  (95, 106),
  (87, 106),
  (96, 107),
  (87, 107),
  (96, 108),
  (87, 108),
  (96, 109),
  (87, 109),
  (97, 110),
  (5, 110),
  (97, 111),
  (5, 111),
  (97, 112),
  (5, 112),
  (98, 113),
  (5, 113),
  (99, 114),
  (5, 114),
  (100, 115),
  (5, 115),
  (100, 116),
  (5, 116),
  (100, 117),
  (5, 117),
  (101, 118),
  (5, 118),
  (101, 119),
  (5, 119),
  (101, 120),
  (5, 120),
  (5, 121),
  (102, 121),
  (5, 122),
  (102, 122),
  (5, 123),
  (103, 123),
  (5, 124),
  (103, 124),
  (104, 125),
  (5, 125),
  (105, 126),
  (5, 126),
  (106, 127),
  (5, 127),
  (106, 128),
  (5, 128),
  (107, 129),
  (6, 129),
  (108, 130),
  (6, 130),
  (109, 131),
  (6, 131),
  (110, 132),
  (6, 132),
  (55, 133),
  (111, 133),
  (112, 134),
  (6, 134);
