// Pre-build step: fingerprint the self-hosted image library.
//
// The image maps in courseImages.js reference stable paths, so a replaced photo
// keeps its URL and browsers serve the stale cached copy until a hard refresh.
// Vite fingerprints JS/CSS but not these files (they are copied verbatim by
// copy-images-to-build.mjs). This writes a content hash the frontend appends as
// ?v=… — the hash changes exactly when any image's content changes, so a normal
// reload picks up replacements, and unchanged rebuilds keep the same hash so
// nothing is re-downloaded pointlessly.
//
// Runs BEFORE `vite build` (the constant is bundled), see package.json.
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, relative } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const imagesDir = join(root, 'public', 'images');
const outFile = join(root, 'resources', 'js', 'data', 'assetVersion.js');

const walk = (dir) => readdirSync(dir, { withFileTypes: true }).flatMap((e) =>
  e.isDirectory() ? walk(join(dir, e.name)) : [join(dir, e.name)]);

const hash = createHash('md5');
if (existsSync(imagesDir)) {
  for (const file of walk(imagesDir).sort()) {
    hash.update(relative(imagesDir, file));
    hash.update(readFileSync(file));
  }
}
const version = hash.digest('hex').slice(0, 8);

const banner = '// AUTO-GENERATED by scripts/asset-version.mjs (pre-build) — do not edit.\n' +
  '// Content hash of public/images; appended as ?v= to self-hosted image URLs\n' +
  '// so replaced photos bust browser caches on a normal reload.\n';
writeFileSync(outFile, `${banner}export const ASSET_V = '${version}';\n`);
console.log(`asset-version: ${version} -> resources/js/data/assetVersion.js`);

// Stamp the same version into the service worker. This is the part that
// actually fixes "old image until I hard-refresh": sw.js caches /build/*
// cache-first and forever, so unless its VERSION changes it keeps serving the
// previous bytes. Its `activate` handler deletes any cache whose name does not
// match the current version, so a new hash wipes the stale images on the next
// page load. Previously VERSION was hand-typed and nobody remembered to bump it
// when a photo changed.
const swFile = join(root, 'public', 'sw.js');
if (existsSync(swFile)) {
  const sw = readFileSync(swFile, 'utf8');
  const next = sw.replace(/^const VERSION = '[^']*';$/m, `const VERSION = '${version}';`);
  if (next === sw && !sw.includes(`const VERSION = '${version}';`)) {
    console.warn('asset-version: WARNING could not find the VERSION line in public/sw.js — stale caches will not be invalidated');
  } else if (next !== sw) {
    writeFileSync(swFile, next);
    console.log(`asset-version: sw.js VERSION -> ${version}`);
  }
}
