// Pre-build step: fingerprint the self-hosted image library.
//
// The image maps in courseImages.js reference stable paths, so a replaced photo
// keeps its URL and browsers serve the stale cached copy until a hard refresh.
// Vite fingerprints JS/CSS but not these files (they are copied verbatim by
// copy-images-to-build.mjs). This writes a content hash the frontend appends as
// ?v=… — the hash changes exactly when any image's content changes, so a normal
// reload picks up replacements, and unchanged rebuilds keep the same hash so
// nothing is re-downloaded pointlessly.
//
// Runs BEFORE `vite build` (the constant is bundled), see package.json.
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, relative } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const imagesDir = join(root, 'public', 'images');
const outFile = join(root, 'resources', 'js', 'data', 'assetVersion.js');

const walk = (dir) => readdirSync(dir, { withFileTypes: true }).flatMap((e) =>
  e.isDirectory() ? walk(join(dir, e.name)) : [join(dir, e.name)]);

const hash = createHash('md5');
if (existsSync(imagesDir)) {
  for (const file of walk(imagesDir).sort()) {
    hash.update(relative(imagesDir, file));
    hash.update(readFileSync(file));
  }
}
const version = hash.digest('hex').slice(0, 8);

const banner = '// AUTO-GENERATED by scripts/asset-version.mjs (pre-build) — do not edit.\n' +
  '// Content hash of public/images; appended as ?v= to self-hosted image URLs\n' +
  '// so replaced photos bust browser caches on a normal reload.\n';
writeFileSync(outFile, `${banner}export const ASSET_V = '${version}';\n`);
console.log(`asset-version: ${version} -> resources/js/data/assetVersion.js`);
